### ISSUE TITLE
Cannot find name 'Proxy'?

### ISSUE THREAD

**Issue by 0w0k** [cwj0417/produce#1]
https://github.com/cwj0417/produce/blob/f4afaeec93b8f4723e55c1ec2e94a3fce63b5e9a/produce.ts#L24

**Comment by cwj0417** [comment]
@youxfans xd, 这个repo流程没有写, 这是个immer的最简demo. 这里有个repo, 有比较详细的介绍和ut. 到对应模块`yarn && yarn test` 可以跑通各个用例 https://github.com/cwj0417/sxdm/tree/main/immer
